version: 2
jobs:
  build:
    working_directory: ~/yii2-validator
    docker:
      - image: composer:latest
    steps:
      - checkout
      - run:
          name: Add composer dependencies
          command: 'composer global require "fxp/composer-asset-plugin:^1.3.1"'
      - run:
          name: Update composer packages
          command: 'composer update'
      - restore_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - vendor

  test56:
    docker:
      - image: php:5.6-fpm-alpine
    steps:
      - checkout
      - run:
          name: Test in PHP 5.6
          command: composer run test

  test70:
    docker:
      - image: php:7.0-fpm-alpine
    steps:
      - checkout
      - run:
          name: Test in PHP 7.0
          command: composer run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test56:
          requires:
            - build
      - test70:
          requires:
            - build
          filters:
            branches:
              only: master