version: 2
jobs:
  build:
    working_directory: ~/yii2-validator
    docker:
      - image: composer:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Setup GitHub Keys
          command: "composer config --global github-oauth.github.com ${GITHUB_KEY}"
      - run:
          name: Add composer dependencies
          command: 'composer global require "fxp/composer-asset-plugin:^1.3.1"'
      - run:
          name: Update composer packages
          command: 'composer update --prefer-dist --no-interaction'
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer

  test56:
    docker:
      - image: php:5.6-fpm-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Install composer
          command: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
      - run:
          name: Setup GitHub Keys
          command: "composer config --global github-oauth.github.com ${GITHUB_KEY}"
      - run:
          name: Add composer dependencies
          command: 'composer global require "fxp/composer-asset-plugin:^1.3.1"'
      - run:
          name: Update composer packages
          command: 'composer update --prefer-dist --no-interaction'
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer
      - run:
          name: Test in PHP 5.6
          command: composer run test

  test70:
    docker:
      - image: php:7.0-fpm-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Install composer
          command: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
      - run:
          name: Setup GitHub Keys
          command: "composer config --global github-oauth.github.com ${GITHUB_KEY}"
      - run:
          name: Add composer dependencies
          command: 'composer global require "fxp/composer-asset-plugin:^1.3.1"'
      - run:
          name: Update composer packages
          command: 'composer update --prefer-dist --no-interaction'
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer
      - run:
          name: Test in PHP 7.0
          command: composer run test

  test71:
    docker:
      - image: php:7.1-fpm-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Install XDebug
          command: 'apk update \
                    && apk add  --no-cache git mysql-client curl libmcrypt libmcrypt-dev openssh-client icu-dev \
                    libxml2-dev freetype-dev libpng-dev libjpeg-turbo-dev g++ make autoconf \
                    && docker-php-source extract \
                    && pecl install xdebug redis \
                    && docker-php-ext-enable xdebug redis \
                    && docker-php-source delete \
                    && docker-php-ext-install mcrypt pdo_mysql soap intl zip \
                    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
                    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
                    && echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
                    && echo "xdebug.remote_handler=dbgp" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
                    && echo "xdebug.remote_connect_back=0" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
                    && rm -rf /tmp/*'
      - run:
          name: Install composer
          command: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
      - run:
          name: Setup GitHub Keys
          command: "composer config --global github-oauth.github.com ${GITHUB_KEY}"
      - run:
          name: Add composer dependencies
          command: 'composer global require "fxp/composer-asset-plugin:^1.3.1"'
      - run:
          name: Update composer packages
          command: 'composer update --prefer-dist --no-interaction'
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer
      - run:
          name: Test in PHP 7.1
          command: composer run test
      - run:
          name: Uploading to codecov.io
          command: 'bash <(curl -s https://codecov.io/bash)'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test56:
          requires:
            - build
      - test70:
          requires:
            - build

      - test71:
          requires:
            - build

          filters:
            branches:
              only: master
