version: 2
jobs:
  build:
    working_directory: ~/yii2-validator
    docker:
      - image: composer:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Setup GitHub Keys
          command: 'composer config --global github-oauth.github.com "${GITHUB_KEY}"'
      - run:
          name: Add composer dependencies
          command: 'composer global require "fxp/composer-asset-plugin:^1.3.1"'
      - run:
          name: Update composer packages
          command: 'composer update --prefer-dist --no-interaction'
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer

  test56:
    docker:
      - image: php:5.6-fpm-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Install composer
          command: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
      - run:
          name: Setup composer
          command: 'apk add git && composer config --global github-protocols https && git config --global url."https://".insteadOf "git://"'
      - run:
          name: Setup GitHub Keys
          command: 'composer config --global github-oauth.github.com "${GITHUB_KEY}"'
      - run:
          name: Add composer dependencies
          command: 'composer global require "fxp/composer-asset-plugin:^1.3.1"'
      - run:
          name: Update composer packages
          command: 'composer update --prefer-dist --no-interaction'
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer
      - run:
          name: Test in PHP 5.6
          command: composer run test

  test70:
    docker:
      - image: php:7.0-fpm-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
      - run:
          name: Install composer
          command: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
      - run:
          name: Setup composer
          command: 'apk add git && composer config --global github-protocols https && git config --global url."https://".insteadOf "git://"'
      - run:
          name: Setup GitHub Keys
          command: 'composer config --global github-oauth.github.com "${GITHUB_KEY}"'
      - run:
          name: Add composer dependencies
          command: 'composer global require "fxp/composer-asset-plugin:^1.3.1"'
      - run:
          name: Update composer packages
          command: 'composer update --prefer-dist --no-interaction'
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer
      - run:
          name: Test in PHP 7.0
          command: composer run test

  test71:
    docker:
      - image: zaherg/php-7.1-xdebug-alpine:latest
    steps:
      - checkout
#      - restore_cache:
#          key: dependency-cache-{{ checksum "composer.json" }}
#      - run:
#          name: Install composer
#          command: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
      - run:
          name: Setup composer
          command: 'composer config --global github-protocols https && git config --global url."https://".insteadOf "git://"'
      - run:
          name: Setup GitHub Keys
          command: 'composer config --global github-oauth.github.com "${GITHUB_KEY}"'
      - run:
          name: Add composer dependencies
          command: 'composer global require "fxp/composer-asset-plugin:^1.3.1"'
      - run:
          name: Update composer packages
          command: 'composer update --prefer-dist --no-interaction'
      - save_cache:
          key: dependency-cache-{{ checksum "composer.json" }}
          paths:
            - vendor
            - ~/.composer
      - run:
          name: Test in PHP 7.1
          command: composer run test
      - run:
          name: Uploading to codecov.io
          command: "bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test56:
          requires:
            - build
      - test70:
          requires:
            - build

      - test71:
          requires:
            - build

          filters:
            branches:
              only: master
